### ISSUE TITLE
Update ?

### ISSUE THREAD

**Issue by dynek** [digistump/arduino-boards-index#5]
Hey,

Is this still being maintained?
Last update was 3 years ago, I started using my Oak only now and Arduino IDE can't download osx-xtensa from arduino.esp8266.com (404 not found).

Thank you

**Comment by pfeerick** [comment]
I've just done PR #6 to correct this. In the mean time, you can try 

https://raw.githubusercontent.com/pfeerick/digistump-boards-index/master/package_digistump_index.json

and see if that works for you. Since updates haven't happened here, I'm in the process of forking and applying any fixes I know about to the digistump cores as I have time and interest ;) 

https://github.com/pfeerick/digistump-boards-index
https://github.com/pfeerick/OakCore
https://github.com/pfeerick/DigistumpArduino

**Comment by dynek** [comment]
That does work, thank you @pfeerick !

**Comment by pfeerick** [comment]
@dynek Excellent, thanks for letting me know! :)
